---
language: python
os: linux
dist: bionic

install: |
  pip install -U cython scipy
  pip install -U pot pytest scikit-learn wasserstein
  pip install tensorflow
  pip install .

script: |
  pytest -v energyflow
  python run_all_examples.py

stages:
  - test

jobs:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8

branches:
  only:
    - master
    - efn2
