---
language: python
os: linux
dist: bionic

install: |
  pip install --upgrade cython scipy
  pip install --upgrade pot pytest scikit-learn wasserstein
  if [ $(python -c "import sys; print(sys.version_info[0])") -eq 2 ]; then
    pip install tensorflow==1.14
  else
    pip install tensorflow
  fi
  pip install .

script:
  - pytest -v energyflow

stages:
  - test

jobs:
  include:
    - python: 2.7
    - python: 3.6
    - python: 3.7
    - python: 3.8

branches:
  only:
    - master
    - efn2
